function scenario = importScenario(input)
%% Purpose:
%
%  Read a scenario exported by the pumpkyn three-body explorer. Return the
%  constants, stationary observer state, and orbit initial states in the
%  rotating barycentric CR3BP frame. No propagation is performed here.
%
%% Inputs:
%
%  input                char or string      Scenario JSON filename or its
%                                           JSON text contents
%
%% Outputs:
%
%  scenario             struct              Imported scenario containing:
%
%    params             struct              Model constants muStar, lStar,
%                                           tStar, rP1 and rP2. Lengths are
%                                           km; tStar is seconds. Remaining
%                                           file metadata, solver, analysis,
%                                           and observer settings are kept
%                                           under their original names.
%
%    xObs               [1 x 6]             Observer [x,y,z,xdot,ydot,zdot]
%                                           in LU/TU; velocity is zero.
%
%    xSat               [N x 6]             One initial state per orbit,
%                                           before applying its offsets.
%
%    tau0               [N x 1]             Orbit periods in TU
%
%    dtau               {N x 1}             Row vector of spacecraft time
%                                           offsets in TU for each orbit.
%                                           An empty vector means no SVs.
%
%    orbits             {N x 1}             Corresponding name, repeat flag
%                                           and source reference, if given.
%
%  analysis.duration and analysis.step remain in TU. Observer elevation_mask
%  remains in degrees. Offset dtau{k}(j) samples orbit k at tau + dtau{k}(j);
%  wrap by tau0(k) only when orbits{k}.repeat is true.
%
%% Example:
%
%  scenario = pumpkyn.util.importScenario('scenario.json');
%  scenario = pumpkyn.util.importScenario(fileread('scenario.json'));
%  [tau,x] = pumpkyn.cr3bp.prop(scenario.tau0(1), ...
%                             scenario.xSat(1,:)',scenario.params.muStar);
%
%% Revision History:
%  Copyright 2026 Coorbital, Inc.
%% -------------------------- Begin Code Sequence -------------------------
if nargin == 0
  jsonText = ...
    "{" + ...
    """format_version"":2," + ...
    """P1"":""Earth""," + ...
    """P2"":""Moon""," + ...
    """created_by"":""pumpkyn three-body explorer""," + ...
    """app_version"":""0.1.0""," + ...
    """frame"":""cr3bp""," + ...
    """units"":""LU/TU""," + ...
    """model"":{" + ...
        """mass_ratio"":0.01215058560962404," + ...
        """length_km"":389703.264829278," + ...
        """time_s"":382981.289129055," + ...
        """p1_radius_km"":6378.1363," + ...
        """p2_radius_km"":1737.1}," + ...
    """solver"":{" + ...
        """method"":""DOP853""," + ...
        """rtol"":1e-11," + ...
        """atol"":1e-13," + ...
        """max_step"":0.03}," + ...
    """observer"":{" + ...
        """primary"":""P2""," + ...
        """position"":[0.987849414390376,3.34258518414417e-35,-0.004457494090435686]," + ...
        """elevation_mask"":0}," + ...
    """analysis"":{" + ...
        """compute_gdop"":true," + ...
        """duration"":6.283185307179586," + ...
        """step"":0.004699968513066041," + ...
        """gdop_threshold"":6," + ...
        """required_satellites"":4}," + ...
    """orbits"":[{" + ...
        """name"":""Pumpkin · 7 petals · S #6""," + ...
        """source"":{""revision"":0,""ref"":""pumpkin-07-s#6""}," + ...
        """state"":[1.02507715239356,0,-0.0468093640036087,0,0.420431282979748,0]," + ...
        """period"":5.95388308652504," + ...
        """repeat"":true," + ...
        """offsets"":[0,0.6615425651694489,1.3230851303388977," + ...
                     "1.9846276955083466,2.6461702606777946,3.3077128258472444," + ...
                     "3.969255391016694,4.630797956186142,5.29234052135559]}]" + ...
    "}";
scenario = pumpkyn.util.importScenario(jsonText);
   return;
end
%Read a filename or decode a JSON object supplied directly:
if ~startsWith(strtrim(input),'{')
    input = fileread(input);
end
     data = jsondecode(input);
%Collect constants and retain the exported solver and analysis settings:
scenario.params = rmfield(data,{'model','observer','orbits'});
scenario.params.muStar = data.model.mass_ratio;
scenario.params.lStar = data.model.length_km;
scenario.params.tStar = data.model.time_s;
scenario.params.rP1 = data.model.p1_radius_km;
scenario.params.rP2 = data.model.p2_radius_km;
scenario.params.observer = rmfield(data.observer,'position');
%The surface observer is stationary in the rotating frame:
scenario.xObs = [reshape(data.observer.position,1,3),zeros(1,3)];
%JSON objects with optional source fields may decode as a cell array:
   orbits = data.orbits;
if isstruct(orbits)
   orbits = num2cell(orbits);
end
        N = numel(orbits);
scenario.xSat = zeros(N,6);
scenario.tau0 = zeros(N,1);
scenario.dtau = cell(N,1);
scenario.orbits = cell(N,1);
for k = 1:N
    scenario.xSat(k,:) = reshape(orbits{k}.state,1,6);
    scenario.tau0(k) = orbits{k}.period;
    scenario.dtau{k} = reshape(orbits{k}.offsets,1,[]);
    scenario.orbits{k} = rmfield(orbits{k},{'state','period','offsets'});
end
end
